name: Release in another repository

env:
  EVENT_BRANCH_NAME: ${{ github.head_ref || github.ref_name || '' }}
  DEFAULT_FRAMEWORK: Maven
  DEFAULT_TAG_ENABLED: true
  DEFAULT_TAG_PATTERN: '^(?!.+(-SNAPSHOT)$).+$'
  DEFAULT_TAG_OVERRIDE: true
  RELEASE_REPOSITORY: Frejdh/releases

on:
  push:
    branches:
      - master
      - main
      - develop
    paths-ignore:
      - '**.md'
      - '.github/workflows/**'
  workflow_dispatch:
    inputs:
      project-framework:
        description: Project framework
        type: choice
        default: Maven
        options:
          - Maven
          - Gradle
          - NPM
          - PyPi

      build-arguments:
        description: Additional arguments for the maven build
        required: false

      commitish:
        description: Git reference (branch/commit) to trigger the build on
        default: ''
        required: false

      create-tag-enabled:
        description: Create a tag
        type: boolean
        default: 'true'

      create-tag-pattern:
        description: The pattern that should generate tags. JavaScript regex syntax
        required: false
        default: '^(?!.+(-SNAPSHOT)$).+$'

      create-tag-allow-override:
        description: Override existing tags
        type: boolean
        default: 'true'

      release-branch-repository:
        description: Target repository that shall contain the release
        default: Frejdh/releases

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release artifacts
        uses: Frejdh/action-release-to-branch@master
        with:
          github-token: ${{ secrets.RELEASE_PAT_TOKEN || secrets.GITHUB_TOKEN }}
          project-framework: ${{ inputs.project-framework || env.DEFAULT_FRAMEWORK }}
          build-arguments: ${{ inputs.build-arguments }}
          commitish: ${{ inputs.commitish || env.EVENT_BRANCH_NAME }}
          create-tag-enabled: ${{ inputs.create-tag-enabled || env.DEFAULT_TAG_ENABLED }}
          create-tag-pattern: ${{ inputs.create-tag-pattern || env.DEFAULT_TAG_PATTERN }}
          create-tag-allow-override: ${{ inputs.create-tag-allow-override || env.DEFAULT_TAG_OVERRIDE }}
          release-branch-repository: ${{ inputs.release-branch-repository || env.RELEASE_REPOSITORY }}
